### ISSUE TITLE
Docker-compose build failes

### ISSUE THREAD

**Issue by pcace** [ramteid/EbayKleinanzeigenCrawler#12]
Hi there, 

i just tried to update the container by pulling updates from the repository and docker-compose build it new. 
i do get some ssl_version errors. any idea what this can be? 

```
rouserot@raspiHome:/home/user/EbayKleinanzeigenCrawler# docker-compose build
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
root@raspiHome:/home/user/EbayKleinanzeigenCrawler# TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
^C
root@raspiHome:/home/user/EbayKleinanzeigenCrawler# TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
^C
root@raspiHome:/home/user/EbayKleinanzeigenCrawler# pip install docker-compose
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: docker-compose in /usr/local/lib/python3.9/dist-packages (1.29.2)
Requirement already satisfied: requests<3,>=2.20.0 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (2.31.0)
Requirement already satisfied: texttable<2,>=0.9.0 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (1.7.0)
Requirement already satisfied: PyYAML<6,>=3.10 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (5.4.1)
Requirement already satisfied: docker[ssh]>=5 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (7.1.0)
Requirement already satisfied: python-dotenv<1,>=0.13.0 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (0.21.1)
Requirement already satisfied: jsonschema<4,>=2.5.1 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (3.2.0)
Requirement already satisfied: distro<2,>=1.5.0 in /usr/lib/python3/dist-packages (from docker-compose) (1.5.0)
Requirement already satisfied: dockerpty<1,>=0.4.1 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (0.4.1)
Requirement already satisfied: websocket-client<1,>=0.32.0 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (0.59.0)
Requirement already satisfied: docopt<1,>=0.6.1 in /usr/local/lib/python3.9/dist-packages (from docker-compose) (0.6.2)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.9/dist-packages (from docker[ssh]>=5->docker-compose) (1.26.16)
Requirement already satisfied: paramiko>=2.4.3 in /usr/local/lib/python3.9/dist-packages (from docker[ssh]>=5->docker-compose) (3.5.0)
Requirement already satisfied: six>=1.3.0 in /usr/lib/python3/dist-packages (from dockerpty<1,>=0.4.1->docker-compose) (1.16.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema<4,>=2.5.1->docker-compose) (24.2.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from jsonschema<4,>=2.5.1->docker-compose) (52.0.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema<4,>=2.5.1->docker-compose) (0.20.0)
Requirement already satisfied: cryptography>=3.3 in /usr/local/lib/python3.9/dist-packages (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (41.0.7)
Requirement already satisfied: pynacl>=1.5 in /usr/local/lib/python3.9/dist-packages (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (1.5.0)
Requirement already satisfied: bcrypt>=3.2 in /usr/local/lib/python3.9/dist-packages (from paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (4.2.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography>=3.3->paramiko>=2.4.3->docker[ssh]>=5->docker-compose) (2.21)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.20.0->docker-compose) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests<3,>=2.20.0->docker-compose) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3,>=2.20.0->docker-compose) (2.10)

root@raspiHome:/home/user/EbayKleinanzeigenCrawler# docker-compose --version
docker-compose version 1.29.2, build unknown

root@raspiHome:/home/user/EbayKleinanzeigenCrawler# python --version
Python 3.9.2
root@raspiHome:/home/user/EbayKleinanzeigenCrawler# git pull
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
```

**Comment by ramteid** [comment]
These errors are related to Docker, not the Crawler. No idea there. I'd recommend the official installation method instead of pip.
Configure your git with 'git config pull.rebase false' and the other warning will disappear.
